# Generated by Django 4.2.2 on 2023-06-21 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nome_social', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=25)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('paciente', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('mt', 'Mulher Trans'), ('mc', 'Mulher Cis'), ('ht', 'Homem Trans'), ('hc', 'Homem Cis'), ('tr', 'Travesti'), ('nb', 'Não Binário'), ('ot', 'Outros')], max_length=2)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.medico')),
            ],
        ),
    ]
